#!/usr/bin/env bash
# Displays the username, user ID, and home directory path for each user in the '/etc/passwd' file.

while IFS=':' read -r username _ uid _ home _; do
  # Display username, user id, and home directory path
  echo "$username:$uid:$home"
done < "/etc/passwd"
root@60ed4ab3482b:/alu-shell/loops_conditions_and_parsing# cat 12-tell_the_story_of_passwd 
#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using a while loop and IFS.

while IFS=':' read -r
