#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for (( i=0; i<10; i++ ))
do
  echo "Best School"
done
root@60ed4ab3482b:/alu-shell/loops_conditions_and_parsing# cat 7-clock 
#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do 
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do 
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
